### ISSUE TITLE
What is the Groovy equivalent of the configure block?

### ISSUE THREAD

**Issue by gredditor** [awslabs/smithy-gradle-plugin#60]
I am trying to use Smithy Gradle plugin to build my model but my build files are in Groovy instead of Kotlin for historical reasons and I am unable to change them.

The the examples for the Smithy Gradle plugin which are in Kotlin, there is a

```
configure<software.amazon.smithy.gradle.SmithyExtension> {
   ...
}
```

I have read the Gradle documentation and cannot figure out what this should be in the Groovy build file version. Any pointers?

**Comment by hpmellema** [comment]
I believe the groovy equivalent would look like: 
```groovy
configure(extension) { ... }
```

See the groovy DSL docs here: https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:configure(java.lang.Iterable,%20groovy.lang.Closure)
