### ISSUE TITLE
How to generate Java classes from the model definition

### ISSUE THREAD

**Issue by gredditor** [awslabs/smithy-gradle-plugin#61]
In an attempt to introduce my company to automated code generation from service definitions, I am looking to get started with defining my APIs with Smithy and use the Gradle plugin to generate the Java code. I followed the complete example as described in https://awslabs.github.io/smithy/2.0/quickstart.html#complete-example

After running gradle build, it did generate the Jar but it does not contain any Java classes.

```
jar -tvf build/libs/smithy-example.jar
     0 Mon Sep 05 12:46:56 PDT 2022 META-INF/
    40 Mon Sep 05 12:44:26 PDT 2022 META-INF/MANIFEST.MF
     0 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/
    15 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/manifest
  2577 Mon Sep 05 12:46:56 PDT 2022 META-INF/smithy/weather.smithy
```

The contents of my project files are **exactly** as shown in the complete example section. After running `gradle build` I expected it to generate the model classes and a client SDK for the service but that does not seem to be the case. Let me know what I am missing or  if I completely misunderstood this project.

**Comment by gredditor** [comment]
Ping

**Comment by hpmellema** [comment]
Per Michaels comment in https://github.com/awslabs/smithy/issues/1390

> We don't currently have any Java code generation for Smithy. It's something we're working on soon. You can see the list of known implementations here: https://awslabs.github.io/smithy/2.0/implementations.html

I do not have any ETA I can share with you, but you might be interested in the documentation on making your own code generator here: https://smithy.io/2.0/guides/building-codegen/index.html

**Comment by Askmecoding** [comment]
I do not see Java as supported language yet. Do you have any update for us? I am curious to know why is Java support still not added. Are there any challenges that we should be aware of if we go with own code generator option mentioned above?
